# telemetry/analysis/tests/BUILD.bazel

load("@rules_python//python:defs.bzl", "py_test")

_NOT_WINDOWS = select({
    "@platforms//os:windows": ["@platforms//:incompatible"],
    "//conditions:default": [],
})

py_test(
    name = "analysis_tests",
    imports = ["../..", "../../.."],
    srcs = ["sample_analysis_test.py"],
    deps = [
        "//apps/telemetry/analysis:analysis_lib",
    ],
    main = "sample_analysis_test.py",
    tags = ["manual"],
    target_compatible_with = _NOT_WINDOWS,
)
