"""MkDocs hook and generator for the CAN Matrix documentation page.

Extracts CAN message definitions, signal layouts, and telemetry bindings from
lib/spec/*.textproto and generates a comprehensive markdown reference table
and raw CSV export.
"""

import glob
import os
import pathlib
import re
import sys

# Safeguard: optimize mkdocs-simple-plugin ignore scanning to prevent
# recursing into Bazel output symlinks (bazel-*) and virtualenvs on Windows dev setups.
try:
    import mkdocs_simple_plugin.simple

    _orig_process = mkdocs_simple_plugin.simple.Simple.process_mkdocsignore_files

    def _fast_process_mkdocsignore_files(self):
        # Scan only root and docs for .mkdocsignore instead of whole tree rglob
        for fname in [".mkdocsignore", "docs/.mkdocsignore"]:
            p = self.root_path / fname
            if p.exists():
                with p.open(mode="r", encoding="utf-8") as txt_file:
                    for line in txt_file:
                        line = line.strip()
                        if line and not line.startswith("#"):
                            self.ignore_glob.add(line)

    mkdocs_simple_plugin.simple.Simple.process_mkdocsignore_files = _fast_process_mkdocsignore_files
except ImportError:
    pass


def parse_textproto(text: str) -> dict:
    """Parses textproto content into nested dictionaries and lists."""
    text = re.sub(r"#.*$", "", text, flags=re.MULTILINE)
    token_pattern = re.compile(r'"(?:[^"\\]|\\.)*"|[^\s{}:"]+|[{}:]')
    tokens = token_pattern.findall(text)

    def parse_block(idx: int):
        res = {}
        while idx < len(tokens):
            tok = tokens[idx]
            if tok == "}":
                return res, idx + 1
            key = tok
            idx += 1
            if idx < len(tokens) and tokens[idx] == ":":
                idx += 1
                val = tokens[idx]
                if val.startswith('"') and val.endswith('"'):
                    val = val[1:-1].encode("raw_unicode_escape").decode("unicode_escape")
                elif re.match(r"^-?\d+$", val):
                    val = int(val)
                elif re.match(r"^-?\d+\.\d+$", val):
                    val = float(val)
                elif val == "true":
                    val = True
                elif val == "false":
                    val = False
                res.setdefault(key, []).append(val)
                idx += 1
            elif idx < len(tokens) and tokens[idx] == "{":
                sub_block, idx = parse_block(idx + 1)
                res.setdefault(key, []).append(sub_block)
            else:
                pass
        return res, idx

    parsed, _ = parse_block(0)
    return parsed


def load_can_spec(spec_dir: str) -> dict:
    """Loads all buses, types, groups, and messages from the spec directory."""
    buses = {}
    enums = {}
    bitfields = {}
    groups = {}
    messages = []

    bus_file = os.path.join(spec_dir, "buses.textproto")
    if os.path.exists(bus_file):
        with open(bus_file, "r", encoding="utf-8") as f:
            data = parse_textproto(f.read())
            for b in data.get("bus", []):
                name = b.get("name", [""])[0]
                buses[name] = b

    types_file = os.path.join(spec_dir, "types.textproto")
    if os.path.exists(types_file):
        with open(types_file, "r", encoding="utf-8") as f:
            data = parse_textproto(f.read())
            for e in data.get("enum_type", []):
                name = e.get("name", [""])[0]
                enums[name] = e
            for bf in data.get("bitfield_type", []):
                name = bf.get("name", [""])[0]
                bitfields[name] = bf

    groups_file = os.path.join(spec_dir, "groups.textproto")
    if os.path.exists(groups_file):
        with open(groups_file, "r", encoding="utf-8") as f:
            data = parse_textproto(f.read())
            for g_reg in data.get("groups", []):
                for g in g_reg.get("group", []):
                    name = g.get("name", [""])[0]
                    groups[name] = g

    msg_files = sorted(glob.glob(os.path.join(spec_dir, "messages", "*.textproto")))
    for mf in msg_files:
        with open(mf, "r", encoding="utf-8") as f:
            data = parse_textproto(f.read())
            for m in data.get("message", []):
                messages.append(m)

    messages.sort(key=lambda m: m.get("can_id", [0])[0])
    return {
        "buses": buses,
        "enums": enums,
        "bitfields": bitfields,
        "groups": groups,
        "messages": messages,
    }


def generate_markdown(spec: dict) -> str:
    """Generates a complete markdown document containing CAN ID tables and CSV export."""
    lines = []
    lines.append("# CAN Message Matrix & Signal Directory")
    lines.append("")
    lines.append("Autogenerated from `lib/spec/*.textproto`. Source of truth for vehicle bus communication.")
    lines.append("")

    messages = spec["messages"]
    total_messages = len(messages)
    total_ids = sum(m.get("quantity", [1])[0] for m in messages)
    total_signals = sum(len(m.get("signal", [])) for m in messages)
    total_buses = len(spec["buses"])

    lines.append('<div class="grid cards" markdown>')
    lines.append(f"- **Total Messages:** {total_messages}")
    lines.append(f"- **Allocated CAN IDs:** {total_ids}")
    lines.append(f"- **Defined Signals:** {total_signals}")
    lines.append(f"- **Buses:** {total_buses}")
    lines.append("</div>")
    lines.append("")

    # Section 1: Message Summary Table
    lines.append("## Message Directory")
    lines.append("")
    lines.append("| CAN ID (Hex) | Dec ID | Name | Transmitter | Receivers | Bus | DLC | Freq (Hz) | Quantity | Description |")
    lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |")

    csv_rows = ["can_id_hex,can_id_dec,message_name,from_board,to_boards,bus,dlc,frequency_hz,quantity,description"]

    for m in messages:
        can_id = m.get("can_id", [0])[0]
        qty = m.get("quantity", [1])[0]
        name = m.get("name", [""])[0]
        from_b = m.get("from_board", [""])[0]
        to_b = ", ".join(m.get("to_boards", ["*"]))
        bus = m.get("bus", [""])[0]
        dlc = m.get("dlc", [8])[0]
        freq = m.get("frequency_hz", [0.0])[0]
        desc = m.get("description", [""])[0]

        if qty == 1:
            hex_id = f"`0x{can_id:03X}`"
            dec_id = f"`{can_id}`"
        else:
            hex_id = f"`0x{can_id:03X}..0x{can_id + qty - 1:03X}`"
            dec_id = f"`{can_id}..{can_id + qty - 1}`"

        freq_str = f"{freq:.1f} Hz" if freq > 0 else "Aperiodic"
        desc_escaped = desc.replace("|", "\\|")
        anchor = f"msg-{name.lower().replace('_', '-')}"
        lines.append(f"| {hex_id} | {dec_id} | [`{name}`](#{anchor}) | `{from_b}` | `{to_b}` | `{bus}` | {dlc}B | {freq_str} | {qty} | {desc_escaped} |")

        csv_desc = f'"{desc}"' if "," in desc else desc
        csv_rows.append(f"0x{can_id:03X},{can_id},{name},{from_b},{to_b},{bus},{dlc},{freq},{qty},{csv_desc}")

    lines.append("")

    # Section 2: CSV Data Block
    lines.append("## Raw CSV Export")
    lines.append("")
    lines.append("??? note \"Click to view / copy raw CSV message table\"")
    lines.append("    ```csv")
    for r in csv_rows:
        lines.append(f"    {r}")
    lines.append("    ```")
    lines.append("")

    # Section 3: Detailed Signal Layouts
    lines.append("## Signal Breakdown by Message")
    lines.append("")

    for m in messages:
        can_id = m.get("can_id", [0])[0]
        qty = m.get("quantity", [1])[0]
        name = m.get("name", [""])[0]
        from_b = m.get("from_board", [""])[0]
        bus = m.get("bus", [""])[0]
        dlc = m.get("dlc", [8])[0]
        freq = m.get("frequency_hz", [0.0])[0]
        desc = m.get("description", [""])[0]
        signals = m.get("signal", [])

        id_title = f"0x{can_id:03X} ({can_id})" if qty == 1 else f"0x{can_id:03X}-0x{can_id+qty-1:03X} ({can_id}-{can_id+qty-1})"
        anchor = f"msg-{name.lower().replace('_', '-')}"

        lines.append(f"### `{name}` {{: #{anchor} }}")
        lines.append(f"**Base ID:** `{id_title}` &bull; **Transmitter:** `{from_b}` &bull; **Bus:** `{bus}` &bull; **DLC:** `{dlc} bytes` &bull; **Rate:** `{freq} Hz`")
        lines.append("")
        lines.append(f"{desc}")
        lines.append("")

        if not signals:
            lines.append("*No signals defined.*")
            lines.append("")
            continue

        lines.append("| Signal | Start Bit | Bit Length | Byte Order | Value Type | Scale | Offset | Bounds [Min, Max] | Unit | Telemetry Binding | Description |")
        lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |")

        for s in signals:
            s_name = s.get("name", [""])[0]
            s_desc = s.get("description", [""])[0].replace("|", "\\|")
            enc = s.get("encoding", [{}])[0]
            log = s.get("logical", [{}])[0]
            tel = s.get("telemetry", [{}])[0]

            start_bit = enc.get("start_bit", [0])[0]
            bit_len = enc.get("bit_length", [0])[0]
            byte_order = enc.get("byte_order", ["LITTLE_ENDIAN"])[0]
            sign = enc.get("sign", ["UNSIGNED"])[0]
            scale = enc.get("scale", [1.0])[0]
            offset = enc.get("offset", [0.0])[0]
            min_val = enc.get("min", ["-"])[0]
            max_val = enc.get("max", ["-"])[0]
            bounds = f"[{min_val}, {max_val}]" if min_val != "-" or max_val != "-" else "-"

            # Type & Unit
            if "physical" in log:
                unit = log["physical"][0].get("unit", ["-"])[0] or "-"
                vtype = f"Physical ({sign.lower()})"
            elif "enum_type" in log:
                unit = "-"
                e_type_name = log["enum_type"][0]
                vtype = f"Enum ([`{e_type_name}`](#enum-{e_type_name.lower()}))"
            elif "bitfield" in log:
                unit = "-"
                bf_name = log["bitfield"][0].get("bitfield_type", [""])[0]
                vtype = f"Bitfield ([`{bf_name}`](#bitfield-{bf_name.lower()}))"
            elif "boolean" in log:
                unit = "-"
                vtype = "Boolean"
            else:
                unit = "-"
                vtype = "Raw"

            if log.get("mux_selector", [False])[0]:
                vtype += " *(Mux Selector)*"
            if enc.get("muxed", [False])[0]:
                mux_val = enc.get("mux_value", [0])[0]
                vtype += f" *(Mux: {mux_val})*"

            # Telemetry
            if tel:
                t_grp = tel.get("group", [""])[0]
                t_fld = tel.get("field", [""])[0]
                t_id = tel.get("id", [""])[0]
                rep = " (rep)" if tel.get("repeated", [False])[0] else ""
                arr = f" [idx:{tel.get('array_index', [0])[0]}]" if "array_index" in tel else ""
                tel_str = f"`{t_grp}.{t_fld}` (#{t_id}){rep}{arr}"
            else:
                tel_str = "*Bus only*"

            lines.append(f"| `{s_name}` | {start_bit} | {bit_len} | {byte_order} | {vtype} | {scale} | {offset} | {bounds} | {unit} | {tel_str} | {s_desc} |")

        lines.append("")

    # Section 4: Types (Enums & Bitfields)
    lines.append("## Enums and Bitfields")
    lines.append("")
    for e_name, e in spec["enums"].items():
        e_desc = e.get("description", [""])[0]
        e_anchor = f"enum-{e_name.lower()}"
        lines.append(f"### Enum `{e_name}` {{: #{e_anchor} }}")
        lines.append(f"{e_desc}")
        lines.append("")
        lines.append("| Value Name | Number | Description |")
        lines.append("| :--- | :--- | :--- |")
        for v in e.get("value", []):
            v_name = v.get("name", [""])[0]
            v_num = v.get("number", [0])[0]
            v_desc = v.get("description", [""])[0].replace("|", "\\|")
            lines.append(f"| `{v_name}` | `{v_num}` | {v_desc} |")
        lines.append("")

    for bf_name, bf in spec["bitfields"].items():
        bf_desc = bf.get("description", [""])[0]
        bf_anchor = f"bitfield-{bf_name.lower()}"
        lines.append(f"### Bitfield `{bf_name}` {{: #{bf_anchor} }}")
        lines.append(f"{bf_desc}")
        lines.append("")
        lines.append("| Bit Index | Flag Name | Telemetry Field | Description |")
        lines.append("| :--- | :--- | :--- | :--- |")
        for idx, bit in enumerate(bf.get("bit", [])):
            b_name = bit.get("name", [""])[0]
            b_desc = bit.get("description", [""])[0].replace("|", "\\|")
            b_tel = bit.get("telemetry", [{}])[0]
            b_tel_str = f"`{b_tel.get('group', [''])[0]}.{b_tel.get('field', [''])[0]}` (#{b_tel.get('id', [''])[0]})" if b_tel else "-"
            lines.append(f"| {idx} | `{b_name}` | {b_tel_str} | {b_desc} |")
        lines.append("")

    # Section 5: Telemetry Groups Ledger
    lines.append("## Telemetry Groups & Ledgers")
    lines.append("")
    lines.append("| Group Name | Next Free ID | Reserved / Tombstoned IDs | Description |")
    lines.append("| :--- | :--- | :--- | :--- |")
    for g_name, g in sorted(spec["groups"].items()):
        next_id = g.get("next_free_id", [1])[0]
        res_ids = ", ".join(str(i) for i in g.get("reserved_ids", [])) or "*None*"
        g_desc = g.get("description", [""])[0].replace("|", "\\|")
        lines.append(f"| `{g_name}` | `{next_id}` | {res_ids} | {g_desc} |")
    lines.append("")

    return "\n".join(lines)


def generate_can_docs(repo_root: pathlib.Path = None):
    """Generates the CAN matrix markdown file."""
    if repo_root is None:
        # Check environment variable for Bazel workspace or calculate from script path
        ws = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
        if ws:
            repo_root = pathlib.Path(ws)
        else:
            repo_root = pathlib.Path(__file__).resolve().parents[2]

    spec_dir = os.path.join(repo_root, "lib", "spec")
    output_path = os.path.join(repo_root, "docs", "can-matrix.md")

    spec = load_can_spec(spec_dir)
    md_content = generate_markdown(spec)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    print(f"Generated CAN Matrix documentation at {output_path}")


def on_pre_build(config):
    """MkDocs hook entrypoint: runs before mkdocs builds the site."""
    generate_can_docs()


if __name__ == "__main__":
    generate_can_docs()
