"""Generates lhre/build_info.hpp from Bazel's stable-status.txt.

Invoked by the build_info_header rule (build_info.bzl) with:
    gen_build_info.py <stable-status.txt> <output.hpp>

The STABLE_* keys come from tools/workspace_status.sh (or .bat on Windows).
To add a new provenance field (e.g. a CAN spec hash):
  1. Emit a STABLE_CAN_SPEC_HASH key from both workspace status scripts (or
     another stamped source).
  2. Add the field to _FIELDS below and to the BuildInfo struct in _TEMPLATE.
Consumers pick it up through lhre::kBuildInfo with no other changes.
"""

import sys

# (struct field, status key, default when the key is missing — e.g. builds
# where no workspace status command is configured)
_FIELDS = [
    ("git_describe", "STABLE_GIT_DESCRIBE", "unknown"),
    ("git_sha", "STABLE_GIT_SHA", "unknown"),
]

_TEMPLATE = """\
// Generated by //tools/firmware:build_info — do not edit.
//
// Build provenance, stamped from git via tools/workspace_status.sh (see
// tools/firmware/gen_build_info.py for how to add fields, e.g. a future CAN
// spec hash).
#pragma once

namespace lhre {{

struct BuildInfo {{
  const char* git_describe;  // `git describe --tags --always`
  const char* git_sha;       // full commit SHA
  bool dirty;                // uncommitted changes to tracked files
  // Future: const char* can_spec_hash;
}};

inline constexpr BuildInfo kBuildInfo = {{
    "{git_describe}",
    "{git_sha}",
    {dirty},
}};

}}  // namespace lhre
"""


def _cpp_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    status_path, out_path = sys.argv[1], sys.argv[2]

    status = {}
    with open(status_path, encoding="utf-8") as f:
        for line in f:
            key, _, value = line.rstrip("\n").partition(" ")
            status[key] = value

    values = {
        field: _cpp_escape(status.get(key, default))
        for field, key, default in _FIELDS
    }
    values["dirty"] = (
        "true" if status.get("STABLE_GIT_DIRTY", "0") == "1" else "false"
    )

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(_TEMPLATE.format(**values))


if __name__ == "__main__":
    main()
