services:
  db_processor:
    image: ${TELEMETRY_GPS_CLASSIFIER_IMAGE:-lhre/telemetry-gps-classifier:dev}
    container_name: gps_classifier_processor
    restart: unless-stopped
    env_file:
      - path: ../../../.env
        required: true
    environment:
      PYTHONUNBUFFERED: 1
      IN_DOCKER: 1
    volumes:
      - ../../../net_configs.json:/app/net_configs.json
    networks:
      - telemetry_network

networks:
  telemetry_network:
    external: true
